# Generated by Django 5.2.3 on 2025-06-21 22:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=5, unique=True, validators=[django.core.validators.RegexValidator(message='Le matricule doit contenir une lettre suivie de 4 chiffres (ex: A1234)', regex='^[A-Z]\\d{4}$')])),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('grade', models.CharField(choices=[('Agent', 'Agent'), ('Maitrise', 'Maitrise'), ('Cadre', 'Cadre')], max_length=10)),
            ],
            options={
                'verbose_name': 'Agent',
                'verbose_name_plural': 'Agents',
            },
        ),
    ]
