# Generated by Django 5.2.3 on 2025-06-21 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='departure_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date de départ'),
        ),
        migrations.AddField(
            model_name='agent',
            name='hire_date',
            field=models.DateField(default='2023-01-01', verbose_name="Date d'embauche"),
        ),
    ]
