# Generated by Django 5.2.3 on 2025-06-23 00:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_function_alter_agent_hire_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='password_changed',
            field=models.BooleanField(default=False, verbose_name='Mot de passe modifié'),
        ),
        migrations.AddField(
            model_name='agent',
            name='permission_level',
            field=models.CharField(choices=[('V', 'Viewer'), ('E', 'Editor'), ('A', 'Administrator'), ('S', 'Super Administrator')], default='V', max_length=1, verbose_name='Niveau de permission'),
        ),
        migrations.AddField(
            model_name='agent',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
