# Generated by Django 5.2.3 on 2025-06-27 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_agent_password_changed_agent_permission_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=100, unique=True)),
                ('color', models.CharField(help_text='Code couleur hexadécimal (ex: #FF0000)', max_length=7)),
            ],
            options={
                'verbose_name': 'Type de Planning',
                'verbose_name_plural': 'Types de Planning',
            },
        ),
    ]
