# Generated by Django 5.2.3 on 2025-06-27 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_scheduletype'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduletype',
            name='short_designation',
            field=models.CharField(default='TYP', help_text='Abréviation en 2-3 lettres majuscules (ex: MAT, APM, NUIT)', max_length=3, unique=True),
        ),
    ]
