# Generated by Django 5.2.3 on 2025-06-27 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_scheduletype_short_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduletype',
            name='short_designation',
            field=models.CharField(blank=True, help_text='Abréviation en 2-3 lettres majuscules (ex: MAT, APM, NUIT)', max_length=3, null=True, unique=True),
        ),
    ]
