# Generated by Django 5.2.3 on 2025-06-30 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_scheduletype_short_designation'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyRotationPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(help_text="Nom du plan (ex: 'Équipe A - Salle de contrôle')", max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description détaillée du plan de rotation', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('schedule_type', models.ForeignKey(help_text="Type d'horaire qui s'applique à toutes les périodes de ce plan", on_delete=django.db.models.deletion.PROTECT, to='core.scheduletype')),
            ],
            options={
                'verbose_name': 'Rythme Quotidien',
                'verbose_name_plural': 'Rythmes Quotidiens',
                'ordering': ['designation'],
            },
        ),
        migrations.CreateModel(
            name='RotationPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text='Date de début de validité de la période')),
                ('end_date', models.DateField(help_text='Date de fin de validité de la période')),
                ('start_time', models.TimeField(help_text='Heure de début quotidienne (ex: 08:00)')),
                ('end_time', models.TimeField(help_text='Heure de fin quotidienne (ex: 16:00)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('daily_rotation_plan', models.ForeignKey(help_text='Plan de rotation auquel appartient cette période', on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='core.dailyrotationplan')),
            ],
            options={
                'verbose_name': 'Période de Rotation',
                'verbose_name_plural': 'Périodes de Rotation',
                'ordering': ['start_date', 'start_time'],
            },
        ),
    ]
