# Generated by Django 5.2.3 on 2025-07-14 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_add_shift_schedule_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftschedule',
            name='type',
            field=models.CharField(choices=[('day', 'Journée'), ('shift', 'Quart')], default='day', max_length=10),
        ),
    ]
