# Generated by Django 5.2.3 on 2025-07-14 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_unique_constraint_daily_plans'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shiftscheduledailyplan',
            unique_together=set(),
        ),
    ]
