# Generated by Django 5.2.3 on 2025-07-16 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_unique_weekday_constraint'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(help_text="Nom du jour férié (ex: 'Fête du Travail', 'Noël')", max_length=200)),
                ('date', models.DateField(help_text='Date du jour férié')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Jour Férié',
                'verbose_name_plural': 'Jours Fériés',
                'ordering': ['date'],
                'unique_together': {('date',)},
            },
        ),
    ]
