# Generated by Django 5.2.3 on 2025-07-17 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_publicholiday'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='publicholiday',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='publicholiday',
            name='date',
            field=models.DateField(error_messages={'unique': 'Un jour férié existe déjà pour cette date.'}, help_text='Date du jour férié', unique=True),
        ),
    ]
