# Generated by Django 5.2.3 on 2025-07-17 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_publicholiday_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Nom du département (ex: 'Ressources Humaines', 'Informatique')", max_length=200, unique=True)),
                ('order', models.PositiveIntegerField(default=10, help_text="Ordre d'affichage hiérarchique (incréments de 10 recommandés)")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Département',
                'verbose_name_plural': 'Départements',
                'ordering': ['order', 'name'],
            },
        ),
    ]
