# Generated by Django 5.2.3 on 2025-07-17 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='order',
            field=models.PositiveIntegerField(help_text="Ordre d'affichage hiérarchique (incréments de 10 recommandés)"),
        ),
    ]
