# Generated by Django 5.2.3 on 2025-07-19 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_department_order'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shiftscheduledailyplan',
            unique_together={('week', 'weekday')},
        ),
    ]
