# Generated by Django 5.2.3 on 2025-07-19 23:01

from django.db import migrations


class Migration(migrations.Migration):
    """
    Documentation migration for daily plan period validation.
    
    This migration documents the addition of validation logic to prevent
    assignment of daily rotation plans that have no periods defined.
    
    Changes include:
    1. Added validation in ShiftScheduleDailyPlan.clean() method
    2. Added validation in shift_schedule_daily_plan_create view
    3. Added filtering in ShiftScheduleDailyPlanForm to only show
       daily rotation plans that have at least one period defined
    """

    dependencies = [
        ('core', '0016_add_daily_plan_validation'),
    ]

    operations = [
        # No database changes - only code validation logic
    ]
