# Generated by Django 5.2.3 on 2025-07-20 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_add_daily_plan_period_validation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(help_text="Nom de l'équipe (ex: 'Équipe Alpha', 'Salle de contrôle A')", max_length=200)),
                ('description', models.TextField(blank=True, help_text="Description détaillée de l'équipe", null=True)),
                ('color', models.CharField(help_text='Code couleur hexadécimal (ex: #FF0000)', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(help_text="Département auquel appartient l'équipe", on_delete=django.db.models.deletion.PROTECT, to='core.department')),
            ],
            options={
                'verbose_name': 'Équipe',
                'verbose_name_plural': 'Équipes',
                'ordering': ['department__order', 'designation'],
            },
        ),
        migrations.CreateModel(
            name='TeamPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, help_text="Date de début d'affectation (optionnel)", null=True)),
                ('end_date', models.DateField(blank=True, help_text="Date de fin d'affectation (optionnel)", null=True)),
                ('considers_holidays', models.BooleanField(default=True, help_text='Ce poste prend-il en compte les jours fériés ?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(blank=True, help_text='Agent assigné à ce poste (optionnel)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.agent')),
                ('function', models.ForeignKey(help_text="Fonction/poste assigné à l'équipe", on_delete=django.db.models.deletion.PROTECT, to='core.function')),
                ('rotation_plan', models.ForeignKey(blank=True, help_text='Plan de roulement assigné à ce poste (optionnel)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.dailyrotationplan')),
                ('team', models.ForeignKey(help_text='Équipe à laquelle appartient ce poste', on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='core.team')),
            ],
            options={
                'verbose_name': "Poste d'Équipe",
                'verbose_name_plural': "Postes d'Équipe",
                'ordering': ['team__designation', 'function__designation'],
                'unique_together': {('team', 'function')},
            },
        ),
    ]
