# Generated by Django 5.2.3 on 2025-07-21 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_team_teamposition'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamposition',
            name='order',
            field=models.PositiveIntegerField(default=1, help_text="Ordre d'affichage du poste dans l'équipe (1, 2, 3...)"),
        ),
    ]
