# Generated by Django 5.2.3 on 2025-07-21 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_teamposition_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teamposition',
            options={'ordering': ['order', 'function__designation'], 'verbose_name': "Poste d'Équipe", 'verbose_name_plural': "Postes d'Équipe"},
        ),
        migrations.AlterUniqueTogether(
            name='teamposition',
            unique_together={('team', 'function'), ('team', 'order')},
        ),
    ]
