# Generated by Django 5.2.3 on 2025-07-21 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_teamposition_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamposition',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='teamposition',
            name='start_date',
        ),
        migrations.AddField(
            model_name='teamposition',
            name='agent_end_date',
            field=models.DateField(blank=True, help_text="Date de fin d'affectation de l'agent", null=True),
        ),
        migrations.AddField(
            model_name='teamposition',
            name='agent_start_date',
            field=models.DateField(blank=True, help_text="Date de début d'affectation de l'agent", null=True),
        ),
        migrations.AddField(
            model_name='teamposition',
            name='rotation_end_date',
            field=models.DateField(blank=True, help_text='Date de fin du plan de roulement', null=True),
        ),
        migrations.AddField(
            model_name='teamposition',
            name='rotation_start_date',
            field=models.DateField(blank=True, help_text='Date de début du plan de roulement', null=True),
        ),
    ]
