# Generated by Django 5.2.3 on 2025-07-26 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_remove_teamposition_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamposition',
            name='rotation_plan',
            field=models.ForeignKey(blank=True, help_text='Roulement hebdomadaire assigné à ce poste (optionnel)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.shiftschedule'),
        ),
    ]
