# Generated by Django 5.2.3 on 2025-07-26 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_teamposition_rotation_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamposition',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='teamposition',
            name='agent_end_date',
        ),
        migrations.RemoveField(
            model_name='teamposition',
            name='agent_start_date',
        ),
        migrations.RemoveField(
            model_name='teamposition',
            name='rotation_end_date',
        ),
        migrations.RemoveField(
            model_name='teamposition',
            name='rotation_plan',
        ),
        migrations.RemoveField(
            model_name='teamposition',
            name='rotation_start_date',
        ),
        migrations.CreateModel(
            name='TeamPositionAgentAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text="Date de début d'affectation")),
                ('end_date', models.DateField(help_text="Date de fin d'affectation")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(help_text='Agent assigné', on_delete=django.db.models.deletion.CASCADE, to='core.agent')),
                ('team_position', models.ForeignKey(help_text="Poste d'équipe concerné", on_delete=django.db.models.deletion.CASCADE, related_name='agent_assignments', to='core.teamposition')),
            ],
            options={
                'verbose_name': "Affectation d'Agent",
                'verbose_name_plural': "Affectations d'Agents",
                'ordering': ['-start_date', 'agent__matricule'],
            },
        ),
        migrations.CreateModel(
            name='TeamPositionRotationAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text='Date de début du roulement')),
                ('end_date', models.DateField(help_text='Date de fin du roulement')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rotation_plan', models.ForeignKey(help_text='Roulement hebdomadaire assigné', on_delete=django.db.models.deletion.CASCADE, to='core.shiftschedule')),
                ('team_position', models.ForeignKey(help_text="Poste d'équipe concerné", on_delete=django.db.models.deletion.CASCADE, related_name='rotation_assignments', to='core.teamposition')),
            ],
            options={
                'verbose_name': 'Affectation de Roulement',
                'verbose_name_plural': 'Affectations de Roulements',
                'ordering': ['-start_date', 'rotation_plan__name'],
            },
        ),
    ]
