# Generated by Django 5.2.3 on 2025-07-27 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_remove_teamposition_agent_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teamposition',
            unique_together={('team', 'order')},
        ),
    ]
